version: "3.4"

services:
  keypublicapi:
      build: ./KeyPublicWebApi
      ports:
        - "5091:80"
      networks:
        - front
        - back-tier
      depends_on:
        - redis

  keyworker:
    build: ./KeyBackground
    command: python3 -u app.py
    volumes:
      - ./KeyBackground:/app
    networks:
      - back-tier
    depends_on:
      - db

  keyapi:
    build: ./KeyManagement
    command: nodemon server.js
    volumes:
      - ./KeyManagement:/app
    ports:
      - "5001:8081"
    networks:
      - back-tier
      - front
    depends_on:
      - db

  db:
    image: postgres:9.4
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier
  
  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

volumes:
  db-data:

networks:
  back-tier:
  front:
